name: 'Download the Vertica RPM'
description: 'Will download the RPM as prep for container building'
runs:
  using: "composite"
  steps:
    - name: Download vertica RPM package
      shell: bash
      env:
          # The script guess-server-upgrade-base-image.sh parses this URL. So,
          # if the structure of this URL ever changes be sure to verify if that
          # script needs an update.
          VERTICA_CE_URL: "https://vertica-community-edition-for-testing.s3.amazonaws.com/XCz9cp7m/vertica-12.0.3-0.x86_64.RHEL6.rpm"
      run: |
        curl $VERTICA_CE_URL -o docker-vertica/packages/vertica-latest.RHEL6.x86_64.rpm
        cp docker-vertica/packages/*rpm docker-vertica-v2/packages
