changesDir: changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [#{{.Custom.Issue}}](https://github.com/vertica/vertica-kubernetes/issues/{{.Custom.Issue}}) {{.Body}}'
kinds:
- Added
- Changed
- Deprecated
- Removed
- Fixed
- Security
custom:
 - key: Issue
   type: int
   minInt: 1
