changesDir: changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [#{{.Custom.Issue}}](https://github.com/vertica/vertica-kubernetes/issues/{{.Custom.Issue}}) {{.Body}}'
kinds:
- label: Added
- label: Changed
- label: Deprecated
- label: Removed
- label: Fixed
- label: Security
custom:
 - key: Issue
   type: int
   minInt: 1
