# (c) Copyright [2021-2024] Open Text.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kuttl.dev/v1beta1
kind: TestSuite
# Each testcase will delete its own namespace if it is successful.  This
# allows us to collect scrutinize for all of the failed tests.
skipDelete: true
# These are overridden when running kuttl from the Makefile
testDirs:
  - tests/e2e-leg-1
  - tests/e2e-leg-1-at-only
  - tests/e2e-leg-2
  - tests/e2e-leg-2-at-only
  - tests/e2e-leg-3
  - tests/e2e-leg-3-at-only
  - tests/e2e-leg-4
  - tests/e2e-leg-5
  - tests/e2e-leg-5-at-only
  - tests/e2e-leg-6
  - tests/e2e-leg-7
  - tests/e2e-leg-8
  - tests/e2e-udx
  - tests/e2e-server-upgrade
  - tests/e2e-server-upgrade-at-only
  - tests/e2e-operator-upgrade-overlays
parallel: 2
timeout: 600
commands:
  # Create the kustomize overlay files to override the image, endpoint, etc.
  - command: scripts/setup-kustomize.sh

  # make dependencies
  - command: make config-transformer vdb-gen install-cert-manager

  - command: kubectl stern --version

  # Ensure the log output directory exists
  - command: mkdir -p int-tests-output

  # We use stern to collect the pod output of any test that creates a pod with
  # the 'stern=include' label.  By default, the output of this is stored in a
  # file in int-tests-output/
  - script: exec kubectl stern --selector stern=include --all-namespaces --timestamps --container-state terminated > int-tests-output/ancillary.log
    background: true

  # We have another stern to collect the output for all of the operators.
  - script: exec kubectl stern --selector app.kubernetes.io/name=verticadb-operator --all-namespaces > int-tests-output/verticadb-operator.log
    background: true

  # And another stern to collect the output from any vertica pods.
  - script: exec kubectl stern --selector app.kubernetes.io/name=vertica --all-namespaces --timestamps > int-tests-output/vertica.log
    background: true

  # Start the operator. Some test steps expects the operator to be in a
  # specific namespace. When deploying the operator at the namespace scope, we
  # only deploy the webhook here.
  - script: make undeploy || true
  - script: if [ "$CONTROLLERS_SCOPE" != "namespace" ]]; then NAMESPACE=verticadb-operator make deploy; fi
  - script: if [ "$CONTROLLERS_SCOPE" = "namespace" ]]; then NAMESPACE=verticadb-operator make deploy-webhook; fi

