resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- envs:
  - operator-envs-with-value
  literals:
  - PREFIX_NAME=verticadb-operator
  - WEBHOOK_CERT_SECRET=verticadb-operator-service-cert
  name: manager-config

generatorOptions:
  disableNameSuffixHash: true
  labels:
    control-plane: verticadb-operator
