apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: verticadb-operator
spec:
  selector:
    matchLabels:
      control-plane: verticadb-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: verticadb-operator
        app.kubernetes.io/name: verticadb-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        image: controller
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:  template-placeholder
        envFrom:
        - configMapRef:
            name: manager-config
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccountName: verticadb-operator-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: "10Mi"
          medium: "Memory"
