name: 'Download kubectl'
description: 'Will download tools for k8s into the current shell'
runs:
  using: "composite"
  steps:
    # Note: we don't download kubectl because it should already be included in
    # the GitHub runner as preinstalled software. Just check that it exists.
    - name: Test kubectl
      shell: bash
      run: |
        kubectl version --client

    - name: Install kubens
      shell: bash
      run: |
        curl -LO "https://github.com/ahmetb/kubectx/releases/download/v0.9.1/kubens"
        sudo install -o root -g root -m 0755 kubens /usr/local/bin/kubens
        kubens --help
    
    - name: Install kubectx   
      shell: bash
      env:
          KUBECTX_URL: https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubectx
      run: |
        curl -fsSLO $KUBECTX_URL
        chmod +x kubectx
        sudo install -o root -g root -m 0755 kubectx /usr/local/bin/kubectx
