alertmanager:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  enabled: true
  # enable tls config
  # https://github.com/prometheus-community/helm-charts/issues/2828
  prometheusSpec:
    web:
      tlsConfig:
        keySecret:
          key: tls.key
          name: prometheus-tls
        cert:
          secret:
            key: tls.crt
            name: prometheus-tls
