apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-role-binding
subjects:
  - kind: ServiceAccount
    name: alloy-sa
    namespace: system
roleRef:
  kind: ClusterRole
  name: alloy-role
  apiGroup: rbac.authorization.k8s.io
