apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager
