apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: verticadb-operator
    vertica.com/svc-type: operator-metrics
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: verticadb-operator
