# permissions for end users to edit verticascrutinizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verticascrutinize-editor-role
rules:
- apiGroups:
  - vertica.com
  resources:
  - verticascrutinizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vertica.com
  resources:
  - verticascrutinize/status
  verbs:
  - get