# permissions for end users to view verticadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verticadb-viewer-role
rules:
- apiGroups:
  - vertica.com
  resources:
  - verticadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vertica.com
  resources:
  - verticadbs/status
  verbs:
  - get
