# permissions for end users to view verticascrutinizes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verticascrutinize-viewer-role
rules:
- apiGroups:
  - vertica.com
  resources:
  - verticascrutinizes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vertica.com
  resources:
  - verticascrutinizes/status
  verbs:
  - get