# permissions for end users to edit verticadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verticadb-editor-role
rules:
- apiGroups:
  - vertica.com
  resources:
  - verticadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vertica.com
  resources:
  - verticadbs/status
  verbs:
  - get
