# permissions for end users to edit verticareplicators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: verticareplicator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: verticadb-operator
    app.kubernetes.io/part-of: verticadb-operator
    app.kubernetes.io/managed-by: kustomize
  name: verticareplicator-editor-role
rules:
- apiGroups:
  - vertica.com
  resources:
  - verticareplicators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vertica.com
  resources:
  - verticareplicators/status
  verbs:
  - get
