---
persistence:
  type: pvc
  enabled: true

# DO NOT DO THIS IN PRODUCTION USECASES
adminUser: admin
adminPassword: adminadminadmin
# CONSIDER USING AN EXISTING SECRET
# Use an existing secret for the admin user.
# admin:
  ## Name of the secret. Can be templated.
#  existingSecret: ""
#  userKey: admin-user
#  passwordKey: admin-password

service:
  enabled: true
  type: ClusterIP

datasources:
  datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          jsonData:
            httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: 1
          access: proxy
          orgId: 1
          url: http://loki-gateway.loki.svc.cluster.local:80
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
