apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: verticadb-sample
spec:
  image: "vertica/vertica-k8s:23.3.0-0-minimal"
  communal:
    # path: "s3://<your-bucket>/"
    endpoint: https://s3.amazonaws.com
  subclusters:
    - name: default_subcluster
      size: 3
