apiVersion: vertica.com/v1
kind: VerticaAutoscaler
metadata:
  name: verticaautoscaler-sample
spec:
  verticaDBName: verticadb-sample
  scalingGranularity: Subcluster
  serviceName: default-subcluster
  customAutoscaler: {}