apiVersion: vertica.com/v1beta1
kind: VerticaAutoscaler
metadata:
  name: verticaautoscaler-sample
spec:
  verticaDBName: verticadb-sample
  subclusters:
    names:
    - defaultsubcluster
  scalePolicy: ResizeSubcluster
