apiVersion: vertica.com/v1beta1
kind: VerticaAutoscaler
metadata:
  name: verticaautoscaler-sample
spec:
  verticaDBName: verticadb-sample
  subclusterServiceName: defaultsubcluster
  scalingGranularity: Pod
