apiVersion: vertica.com/v1beta1
kind: VerticaAutoscaler
metadata:
  name: as-sample-custom-metrics
spec:
  verticaDBName: verticadb-sample
  # The serviceName should be the name of your subcluster
  serviceName: sc1
  scalingGranularity: Pod
  customAutoscalerSpec:
    minReplicas: 3
    maxReplicas: 10
    metrics:    
    - metric:
        type: Pods
        pods:
          metric:
            # The name of the mapped Kubernetes metric name
            name: vertica_query_requests_attempted_rate_per_second
          target:
            type: AverageValue
            averageValue: 20000m