# (c) Copyright [2021-2024] Open Text.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is used to verify the public artifacts through the GitHub CI.
# When making changes to this file, ensure you run the verify-public-artifact
# workflow. See: .github/workflows/verify-public-artifacts.yml

apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: verticadb-sample
  annotations:
    vertica.com/include-uid-in-path: "true"
    # This controls the deployment method. Any server version that is older
    # than 24.1.0 (e.g. 23.x.0, 12.0.x, etc.) will want this to set false so
    # the operator treats it as an admintools deployment. Server versions that
    # are 24.1.0 or newer will want this set to true to deploy with vclusterops.
    vertica.com/vcluster-ops: "true"
spec:
  # Let the operator pick the latest image. It will be an image that uses
  # vclusterOps deployment. If you want to deploy with admintools, uncomment the
  # next line and update the annotations.
  #image: "opentext/vertica-k8s:23.3.0-0-minimal" # ensure vertica.com/vcluster-ops is false
  communal:
    path: "s3://nimbusdb/db"
    endpoint: "http://minio"
    credentialSecret: s3-auth
  subclusters:
    - name: defaultsubcluster
      size: 3
      # The CPU resource setting is here is a sample.  We set it so that this
      # will work with the sample VerticaAutoscaler resource.  The actual amount
      # should be sized according to:
      # https://www.vertica.com/kb/Recommendations-for-Sizing-Vertica-Nodes-and-Clusters/Content/Hardware/Recommendations-for-Sizing-Vertica-Nodes-and-Clusters.htm
      resources:
        requests:
          cpu: 500m
