name: 'Setup e2e environment'
description: 'Will setup the environment to run e2e tests'
runs:
  using: "composite"
  steps:
    - name: Set up Go and kubectx
      uses: ./.github/actions/setup-go-kctx

    - name: Install kubectl and related tools
      uses: ./.github/actions/setup-kubectl

    - name: Download all the docker image for PRs
      uses: actions/download-artifact@v2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Load the docker images for PRs
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        docker load --input full-vertica-image.tar
        docker load --input minimal-vertica-image.tar
        docker load --input operator-image.tar
        docker load --input vlogger-image.tar
        docker image ls -a

