name: 'Setup e2e environment'
description: 'Will setup the environment to run e2e tests'
runs:
  using: "composite"
  steps:
    - name: Set up Go and kubectx
      uses: ./.github/actions/setup-go-kctx

    - name: Install kubectl and related tools
      uses: ./.github/actions/setup-kubectl
    
    - name: Download vertica RPM package
      shell: bash
      env:
          VERTICA_CE_URL: "https://vertica-community-edition-for-testing.s3.amazonaws.com/XCz9cp7m/vertica-12.0.0-0.x86_64.RHEL6.rpm"
      run: |
        curl $VERTICA_CE_URL -o docker-vertica/packages/vertica-x86_64.RHEL6.latest.rpm
