name: 'Setup e2e environment'
description: 'Will setup the environment to run e2e tests'
runs:
  using: "composite"
  steps:
    - name: Set up Go and kubectx
      uses: ./.github/actions/setup-go-kctx

    - name: Install kubectl and related tools
      uses: ./.github/actions/setup-kubectl
