#!/bin/bash

# (c) Copyright [2021-2022] Micro Focus or one of its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A script that will lint the Dockerfile's in the repo

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_DIR=$(dirname $SCRIPT_DIR)
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No color

set -o errexit
set -o pipefail

for dir in docker-operator docker-vertica docker-vlogger
do
    F=$dir/Dockerfile
    printf "Checking ${YELLOW}$F${NC}\n"
    docker run --rm -i hadolint/hadolint < $REPO_DIR/$F
    printf "\xE2\x9C\x94 Success${NC}\n"
done
