#!/bin/bash

# (c) Copyright [2021-2023] Open Text.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A script that will lint the Dockerfile's in the repo

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_DIR=$(dirname $SCRIPT_DIR)
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No color

set -o errexit
set -o pipefail

LINT_IMAGE=hadolint/hadolint:2.12.0
docker pull $LINT_IMAGE

for dir in docker-operator docker-vertica docker-vlogger docker-vertica-v2
do
    F=$dir/Dockerfile
    printf "Checking ${YELLOW}$F${NC}\n"
    # Ignore the following rules:
    # DL3008, DL3018, DL3033: All are warnings about pinning versions in
    #         package install.  We are going to ignore it so that we always
    #         pull the latest version of the package without having to update
    #         the Dockerfile.
    docker run --rm -i $LINT_IMAGE hadolint --ignore=DL3008 --ignore=DL3018 --ignore=DL3033 - < $REPO_DIR/$F
    printf "\xE2\x9C\x94 Success${NC}\n"
done
