name: Dockerfile lint

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Lint
      run: |
        scripts/dockerfile-lint
