name: Dockerfile lint

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Lint vlogger
      uses: hadolint/hadolint-action@v2.0.0
      with:
        target: docker-vlogger/Dockerfile

    - name: Lint operator
      uses: hadolint/hadolint-action@v2.0.0
      with:
        target: docker-operator/Dockerfile

    - name: Lint vertica
      uses: hadolint/hadolint-action@v2.0.0
      with:
        target: docker-vertica/Dockerfile
