name: e2e (s3) tests

on: 
  push:
     branches: [main, vnext]
  pull_request:
  workflow_dispatch:
    inputs:
      parallel:
        description: 'Maximum number of tests to run at once'
        required: false

jobs:

  e2e-s3:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up e2e environment
      uses: ./.github/actions/setup-e2e
      
    - name: Run e2e tests
      run: |
        E2E_PARALLELISM=${{ github.event.inputs.parallel }}
        [ ! -z "$E2E_PARALLELISM" ] && export E2E_PARALLELISM
        export MINIMAL_VERTICA_IMG=YES
        scripts/run-k8s-int-tests.sh

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: logs-e2e-s3
        path: /home/runner/work/vertica-kubernetes/vertica-kubernetes/int-tests-output/*

