name: e2e (leg-8) tests

on: 
  workflow_call:
    inputs:
      vlogger-image:
        type: string
        required: false
      operator-image:
        type: string
        required: false
      vertica-image:
        type: string
        required: false
    secrets:
      DOCKERHUB_USERNAME:
        description: 'When working with images from docker.io, this is the username for login purposes'
        required: true
      DOCKERHUB_TOKEN:
        description: 'When working with images from docker.io, this is the password for login purposes'
        required: true
  workflow_dispatch:
    inputs:
      vlogger-image:
        description: 'Name of the vertica logger image'
        type: string
        required: false
      operator-image:
        description: 'Name of the operator image'
        type: string
        required: false
      vertica-image:
        description: 'Name of the vertica server image'
        type: string
        required: false

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up e2e environment
      uses: ./.github/actions/setup-e2e
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: ${{ startsWith(inputs.vertica-image, 'docker.io') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run e2e tests
      run: |
        export KUSTOMIZE_CFG=tests/kustomize-defaults-azb-ci.cfg
        export OPERATOR_IMG=${{ inputs.operator-image }}
        export VERTICA_IMG=${{ inputs.vertica-image }}
        export VLOGGER_IMG=${{ inputs.vlogger-image }}
        # Initial deployments in the tests are admintools. They will transition
        # to vclusterOps through upgrades.
        export VERTICA_DEPLOYMENT_METHOD=admintools
        export E2E_TEST_DIRS="tests/e2e-leg-8"
        # Leg 8 is tests with a set of fixed server images. The image must be
        # at least a 24.2.0+. If it is older, then we complete this leg as a
        # no-op.
        if scripts/is-image.sh -i $VERTICA_IMG older 24.2.0
        then
          echo "Old version detected, skipping all of the tests"
          exit 0
        fi
        scripts/run-k8s-int-tests.sh -s -e tests/external-images-azb-ci.txt

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-e2e-leg-8
        path: ${{ github.workspace }}/int-tests-output/*
