name: e2e (leg-4) tests

on: 
  workflow_call:
    inputs:
      vlogger-image:
        type: string
        required: false
      operator-image:
        type: string
        required: false
      vertica-image:
        type: string
        required: false
      vertica-deployment-method:
        type: string
        required: false
      vertica-superuser-name:
        type: string
        required: false
        default: myadmin
    secrets:
      DOCKERHUB_USERNAME:
        description: 'When working with images from docker.io, this is the username for login purposes'
        required: true
      DOCKERHUB_TOKEN:
        description: 'When working with images from docker.io, this is the password for login purposes'
        required: true
  workflow_dispatch:
    inputs:
      vlogger-image:
        description: 'Name of the vertica logger image'
        type: string
        required: false
      operator-image:
        description: 'Name of the operator image'
        type: string
        required: false
      vertica-image:
        description: 'Name of the vertica server image'
        type: string
        required: false
      vertica-deployment-method:
        description: 'Vertica deployment method'
        type: choice
        required: false
        default: admintools
        options:
        - admintools
        - vclusterops
      vertica-superuser-name:
        description: 'Vertica superuser name'
        type: string
        required: false
        default: myadmin

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up e2e environment
      uses: ./.github/actions/setup-e2e
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ startsWith(inputs.vertica-image, 'docker.io') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run e2e tests
      run: |
        export VERTICA_IMG=${{ inputs.vertica-image }}
        export OPERATOR_IMG=${{ inputs.operator-image }}
        export VLOGGER_IMG=${{ inputs.vlogger-image }}
        export E2E_TEST_DIRS="tests/e2e-leg-4"
        export VERTICA_DEPLOYMENT_METHOD=${{ inputs.vertica-deployment-method }}
        export VERTICA_SUPERUSER_NAME=${{ inputs.vertica-superuser-name }}
        if [ -z "${VERTICA_SUPERUSER_NAME}" -o "${VERTICA_DEPLOYMENT_METHOD}" != "vclusterops" ]; then 
          export VERTICA_SUPERUSER_NAME="dbadmin"
        fi
        # All helm deployments will use cert-manager to create the webhook cert
        export HELM_OVERRIDES="--set webhook.certSource=cert-manager"
        scripts/run-k8s-int-tests.sh -s -e tests/external-images-s3-ci.txt

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: logs-e2e-leg-4-${{ inputs.vertica-deployment-method }}
        path: ${{ github.workspace }}/int-tests-output/*

