name: e2e (leg-1) tests

on: 
  workflow_call:
    inputs:
      vlogger-image:
        type: string
        required: false
      operator-image:
        type: string
        required: false
      vertica-image:
        type: string
        required: false
      artifact-suffix:
        type: string
        required: false
      vertica-deployment-method:
        type: string
        required: false
    secrets:
      DOCKERHUB_USERNAME:
        description: 'When working with images from docker.io, this is the username for login purposes'
        required: true
      DOCKERHUB_TOKEN:
        description: 'When working with images from docker.io, this is the password for login purposes'
        required: true
  workflow_dispatch:
    inputs:
      vlogger-image:
        description: 'Name of the vertica logger image'
        type: string
        required: false
      operator-image:
        description: 'Name of the operator image'
        type: string
        required: false
      vertica-image:
        description: 'Name of the vertica server image'
        type: string
        required: false
      artifact-suffix:
        description: 'Version of the suffix artifact file'
        type: string
        required: false
      vertica-deployment-method:
        description: 'Vertica deployment method'
        type: choice
        required: false
        default: admintools
        options:
        - admintools
        - vclusterops

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up e2e environment
      uses: ./.github/actions/setup-e2e
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ startsWith(inputs.vertica-image, 'docker.io') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run e2e tests
      run: |
        export KUSTOMIZE_CFG=tests/kustomize-defaults-azb-ci.cfg
        export VERTICA_IMG=${{ inputs.vertica-image }}
        export OPERATOR_IMG=${{ inputs.operator-image }}
        export VLOGGER_IMG=${{ inputs.vlogger-image }}
        export E2E_TEST_DIRS=tests/e2e-leg-1
        export DEPLOY_WITH=olm
        export VERTICA_DEPLOYMENT_METHOD=${{ inputs.vertica-deployment-method }}
        if [ "${VERTICA_DEPLOYMENT_METHOD}" != "vclusterops" ]; then E2E_TEST_DIRS+=" tests/e2e-leg-1-at-only"; fi
        export NMA_RUNNING_MODE=sidecar
        scripts/run-k8s-int-tests.sh -s -e tests/external-images-azb-ci.txt

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: logs-e2e-leg-1-${{ inputs.vertica-deployment-method }}${{ inputs.artifact-suffix }}
        path: ${{ github.workspace }}/int-tests-output/*
