name: e2e (leg-8) tests

on: 
  workflow_call:
    inputs:
      operator-image:
        type: string
        required: false
    secrets:
      DOCKERHUB_USERNAME:
        description: 'When working with images from docker.io, this is the username for login purposes'
        required: true
      DOCKERHUB_TOKEN:
        description: 'When working with images from docker.io, this is the password for login purposes'
        required: true
  workflow_dispatch:
    inputs:
      operator-image:
        description: 'Name of the operator image'
        type: string
        required: false

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up e2e environment
      uses: ./.github/actions/setup-e2e
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: ${{ startsWith(inputs.vertica-image, 'docker.io') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run e2e tests
      run: |
        export KUSTOMIZE_CFG=tests/kustomize-defaults-azb-ci.cfg
        export OPERATOR_IMG=${{ inputs.operator-image }}
        export E2E_TEST_DIRS="tests/e2e-leg-8"
        scripts/run-k8s-int-tests.sh -s -e tests/external-images-azb-ci.txt

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-e2e-leg-8
        path: ${{ github.workspace }}/int-tests-output/*
